export const POLICY_REASON_CODES = [
  'POLICY_REVOKED',
  'POLICY_INACTIVE',
  'POLICY_ID_MISMATCH',
  'POLICY_REVISION_MISMATCH',
  'POLICY_REVISION_HASH_MISMATCH',
  'ADAPTER_UNSUPPORTED',
  'GRANT_INACTIVE',
  'POLICY_NOT_YET_VALID',
  'POLICY_EXPIRED',
  'ACTION_EXPIRED',
  'ORG_MISMATCH',
  'ACCOUNT_MISMATCH',
  'AGENT_MISMATCH',
  'AGENT_INACTIVE',
  'AGENT_KEY_VERSION_MISMATCH',
  'CHAIN_MISMATCH',
  'TARGET_DENIED',
  'SELECTOR_DENIED',
  'ASSET_DENIED',
  'RECIPIENT_DENIED',
  'ACTION_AMOUNT_INVALID',
  'ACTION_LIMIT_EXCEEDED',
  'BUDGET_UNAVAILABLE',
  'ACTION_COUNT_LIMIT_EXCEEDED',
  'CUMULATIVE_LIMIT_EXCEEDED',
  'NONCE_INVALID',
  'APPROVAL_REQUIRED',
  'HUMAN_APPROVED',
  'APPROVAL_DENIED',
  'POLICY_PASS',
] as const;

export type PolicyReasonCode = (typeof POLICY_REASON_CODES)[number];
export type PolicyVerdict = 'ALLOW' | 'BLOCK' | 'HOLD';

export interface PolicyDecision {
  readonly verdict: PolicyVerdict;
  readonly reason: PolicyReasonCode;
}
